#============================================================================
# webmin post installation
# from http://doxfer.webmin.com/Webmin/Installation
#============================================================================
#
#  Post installation
#  -----------------
#
#  Once started you can access webmin at the ip or web address you
#  supplied or were given by the system at the port.
#
#  Example:
#  -------
#
#      $ https://192.168.1.100:10000/

exit
# do it manually for now

#
#  If the webmin server doesn't respond, you might need to adjust
#  firewall settings to allow port 10000
#
#  IPTables
#  --------
#
#  Make sure that the Linux Firewall does allow port 10000.
#

iptables-save > /tmp/tabsav
vi /tmp/tabsav
iptables-restore < /tmp/tabsav

#
#  Use the commands above to make the firewall rules look like below

# Generated by iptables-save on 2017-07-17
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [3044:1198306]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 10000 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
# Completed on 2017-07-17

#  Firewalld
#  ---------

firewall-cmd --zone=public --add-port=10000/tcp --permanent
firewall-cmd --reload
